In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import re

# This Notebook requires the whole UNCOVER dataset to run . Only for Reference

### With this notebook, we selected relevant files for our project
### dataset is the parent folder and contains the whole UNCOVER dataset

In [2]:
import csv

with open('.dataset/uncover/UNCOVER_v4/UNCOVER/howsmyflattening/howsmyflattening/ontario-testing-data.csv', 'r') as f:
    d_reader = csv.DictReader(f)

    #get fieldnames from DictReader object and store in list
    headers = d_reader.fieldnames

    print(headers)

['id', 'date', 'negative', 'investigation', 'positive', 'resolved', 'deaths', 'total', 'hospitalized', 'icu', 'ventilator']

In [3]:
def listToString(s):  
    
     
    str1 = ""  
    
      
    for ele in s:  
        str1 += ele   
    
      
    return str1

In [4]:
Files={'File':[],'Score':[]}

In [5]:
columns=[]
import os
count=0
patterns=['ventilator','ICU','doctor','bed','ventilatore','terapia_intensiva','medico','letto','ventilateur','m√©decin','lit',
          'ventilador','UCI','medica','cama']
for subdir, dirs, files in os.walk('./dataset/uncover'):
    for filename in files:
        filepath = subdir + os.sep + filename
        if filepath.endswith(".csv"):
            with open(filepath, 'r') as f:
                d_reader = csv.DictReader(f)
    #get fieldnames from DictReader object and store in list
                score=0
                try:
                    headers = d_reader.fieldnames
                    text=listToString(headers)
                    for pattern in patterns:
                        if re.search(pattern,text):
                            score+=1
                    Files['File'].append(filepath)
                    Files['Score'].append(score)
                except:

In [23]:
File_Data=pd.DataFrame.from_dict(Files)

In [24]:
File_Data.sort_values('Score',ascending=False).head(50)

,File,Score
106,./archive\UNCOVER\howsmyflattening\ontario-icu-capacity.csv,2
101,./archive\UNCOVER\hifld\hifld\nursing-homes.csv,2
197,./archive\UNCOVER_v4\UNCOVER\our_world_in_data\coronavirus-disease-covid-19-statistics-and-research.csv,2
196,./archive\UNCOVER_v4\UNCOVER\our_world_in_data\coronavirus-disease-covid-19-statistics-and-research (1).csv,2
16,./archive\RDSC-07-30-Update\RDSC-07-30-Update\covid_tracking_project\covid-statistics-by-us-states-totals.csv,2
15,./archive\RDSC-07-30-Update\RDSC-07-30-Update\covid_tracking_project\covid-statistics-by-us-states-daily-updates.csv,2
163,./archive\UNCOVER_v4\UNCOVER\covid_tracking_project\covid-statistics-by-us-states-daily-updates.csv,2
164,./archive\UNCOVER_v4\UNCOVER\covid_tracking_project\covid-statistics-by-us-states-totals.csv,2
30,./archive\RDSC-07-30-Update\RDSC-07-30-Update\howsmyflattening\ontario-icu-capacity.csv,2
98,./archive\UNCOVER\hifld\hifld\aircraft-landing-facilities.csv,2
176,./archive\UNCOVER_v4\UNCOVER\howsmyflattening\howsmyflattening\ontario-icu-capacity.csv,2
49,./archive\RDSC-07-30-Update\RDSC-07-30-Update\our_world_in_data\coronavirus-disease-covid-19-statistics-and-research.csv,2
78,./archive\UNCOVER\covid_tracking_project\covid-statistics-by-us-states-totals.csv,2
165,./archive\UNCOVER_v4\UNCOVER\covid_tracking_project\covid-statistics-for-all-us-daily-updates.csv,1
77,./archive\UNCOVER\covid_tracking_project\covid-statistics-by-us-states-daily-updates.csv,1
171,./archive\UNCOVER_v4\UNCOVER\government_of_ontario\status-of-covid-19-cases-in-ontario.csv,1
54,./archive\RDSC-07-30-Update\RDSC-07-30-Update\statistics_canada\open-database-of-healthcare-facilities.csv,1
68,./archive\UNCOVER\coders_against_covid\crowd-sourced-covid-19-testing-locations.csv,1
69,./archive\UNCOVER\county_health_rankings\county_health_rankings\us-county-health-rankings-2020.csv,1
154,./archive\UNCOVER_v4\UNCOVER\coders_against_covid\crowd-sourced-covid-19-testing-locations.csv,1
177,./archive\UNCOVER_v4\UNCOVER\howsmyflattening\howsmyflattening\ontario-testing-data.csv,1
178,./archive\UNCOVER_v4\UNCOVER\ihme\projected-hospital-resource-use-based-on-covid-19-deaths.csv,1
80,./archive\UNCOVER\covid_tracking_project\covid-statistics-for-all-us-totals.csv,1
79,./archive\UNCOVER\covid_tracking_project\covid-statistics-for-all-us-daily-updates.csv,1
185,./archive\UNCOVER_v4\UNCOVER\johns_hopkins_csse\johns-hopkins-covid-19-daily-dashboard-cases-by-states.csv,1
85,./archive\UNCOVER\esri_covid-19\esri_covid-19\cdphe-health-facilities.csv,1
87,./archive\UNCOVER\esri_covid-19\esri_covid-19\definitive-healthcare-usa-hospital-beds.csv,1
92,./archive\UNCOVER\harvard_global_health_institute\hospital-capacity-by-state-20-population-contracted.csv,1
93,./archive\UNCOVER\harvard_global_health_institute\hospital-capacity-by-state-40-population-contracted.csv,1
94,./archive\UNCOVER\harvard_global_health_institute\hospital-capacity-by-state-60-population-contracted.csv,1
99,./archive\UNCOVER\hifld\hifld\hospitals.csv,1
137,./archive\UNCOVER\statistics_canada\open-database-of-healthcare-facilities.csv,1
107,./archive\UNCOVER\howsmyflattening\ontario-testing-data.csv,1
108,./archive\UNCOVER\ihme\projected-hospital-resource-use-based-on-covid-19-deaths.csv,1
133,./archive\UNCOVER\regional_sources\department_of_civil_protection\covid-19-italy-situation-monitoring-by-region.csv,1
114,./archive\UNCOVER\johns_hopkins_csse\johns-hopkins-covid-19-daily-dashboard-cases-by-country.csv,1
115,./archive\UNCOVER\johns_hopkins_csse\johns-hopkins-covid-19-daily-dashboard-cases-by-states.csv,1
126,./archive\UNCOVER\ontario_government\status-of-covid-19-cases-in-ontario (1).csv,1
184,./archive\UNCOVER_v4\UNCOVER\johns_hopkins_csse\johns-hopkins-covid-19-daily-dashboard-cases-by-country.csv,1
166,./archive\UNCOVER_v4\UNCOVER\covid_tracking_project\covid-statistics-for-all-us-totals.csv,1
39,./archive\RDSC-07-30-Update\RDSC-07-30-Update\johns_hopkins_csse\johns-hopkins-covid-19-daily-dashboard-cases-by-states.csv,1
5,./archive\RDSC-07-30-Update\RDSC-07-30-Update\coders_against_covid\crowd-sourced-covid-19-testing-locations.csv,1
38,./archive\RDSC-07-30-Update\RDSC-07-30-Update\johns_hopkins_csse\johns-hopkins-covid-19-daily-dashboard-cases-by-country.csv,1
19,./archive\RDSC-07-30-Update\RDSC-07-30-Update\department_of_civil_protection\covid-19-italy-situation-monitoring-by-region.csv,1
17,./archive\RDSC-07-30-Update\RDSC-07-30-Update\covid_tracking_project\covid-statistics-for-all-us-daily-updates.csv,1
22,./archive\RDSC-07-30-Update\RDSC-07-30-Update\github\crowd-sourced-covid-19-testing-locations.csv,1
201,./archive\UNCOVER_v4\UNCOVER\regional_sources\department_of_civil_protection\covid-19-italy-situation-monitoring-by-region.csv,1
194,./archive\UNCOVER_v4\UNCOVER\ontario_government\status-of-covid-19-cases-in-ontario.csv,1
32,./archive\RDSC-07-30-Update\RDSC-07-30-Update\ihme\projected-hospital-resource-use-based-on-covid-19-deaths.csv,1
207,./archive\UNCOVER_v4\UNCOVER\statistics_canada\open-database-of-healthcare-facilities.csv,1

In [25]:
Sorted=File_Data.sort_values('Score',ascending=False).head(50)

In [26]:
pd.set_option('display.max_colwidth', None)

In [27]:
Sorted

,File,Score
106,./archive\UNCOVER\howsmyflattening\ontario-icu-capacity.csv,2
101,./archive\UNCOVER\hifld\hifld\nursing-homes.csv,2
197,./archive\UNCOVER_v4\UNCOVER\our_world_in_data\coronavirus-disease-covid-19-statistics-and-research.csv,2
196,./archive\UNCOVER_v4\UNCOVER\our_world_in_data\coronavirus-disease-covid-19-statistics-and-research (1).csv,2
16,./archive\RDSC-07-30-Update\RDSC-07-30-Update\covid_tracking_project\covid-statistics-by-us-states-totals.csv,2
15,./archive\RDSC-07-30-Update\RDSC-07-30-Update\covid_tracking_project\covid-statistics-by-us-states-daily-updates.csv,2
163,./archive\UNCOVER_v4\UNCOVER\covid_tracking_project\covid-statistics-by-us-states-daily-updates.csv,2
164,./archive\UNCOVER_v4\UNCOVER\covid_tracking_project\covid-statistics-by-us-states-totals.csv,2
30,./archive\RDSC-07-30-Update\RDSC-07-30-Update\howsmyflattening\ontario-icu-capacity.csv,2
98,./archive\UNCOVER\hifld\hifld\aircraft-landing-facilities.csv,2
176,./archive\UNCOVER_v4\UNCOVER\howsmyflattening\howsmyflattening\ontario-icu-capacity.csv,2
49,./archive\RDSC-07-30-Update\RDSC-07-30-Update\our_world_in_data\coronavirus-disease-covid-19-statistics-and-research.csv,2
78,./archive\UNCOVER\covid_tracking_project\covid-statistics-by-us-states-totals.csv,2
165,./archive\UNCOVER_v4\UNCOVER\covid_tracking_project\covid-statistics-for-all-us-daily-updates.csv,1
77,./archive\UNCOVER\covid_tracking_project\covid-statistics-by-us-states-daily-updates.csv,1
171,./archive\UNCOVER_v4\UNCOVER\government_of_ontario\status-of-covid-19-cases-in-ontario.csv,1
54,./archive\RDSC-07-30-Update\RDSC-07-30-Update\statistics_canada\open-database-of-healthcare-facilities.csv,1
68,./archive\UNCOVER\coders_against_covid\crowd-sourced-covid-19-testing-locations.csv,1
69,./archive\UNCOVER\county_health_rankings\county_health_rankings\us-county-health-rankings-2020.csv,1
154,./archive\UNCOVER_v4\UNCOVER\coders_against_covid\crowd-sourced-covid-19-testing-locations.csv,1
177,./archive\UNCOVER_v4\UNCOVER\howsmyflattening\howsmyflattening\ontario-testing-data.csv,1
178,./archive\UNCOVER_v4\UNCOVER\ihme\projected-hospital-resource-use-based-on-covid-19-deaths.csv,1
80,./archive\UNCOVER\covid_tracking_project\covid-statistics-for-all-us-totals.csv,1
79,./archive\UNCOVER\covid_tracking_project\covid-statistics-for-all-us-daily-updates.csv,1
185,./archive\UNCOVER_v4\UNCOVER\johns_hopkins_csse\johns-hopkins-covid-19-daily-dashboard-cases-by-states.csv,1
85,./archive\UNCOVER\esri_covid-19\esri_covid-19\cdphe-health-facilities.csv,1
87,./archive\UNCOVER\esri_covid-19\esri_covid-19\definitive-healthcare-usa-hospital-beds.csv,1
92,./archive\UNCOVER\harvard_global_health_institute\hospital-capacity-by-state-20-population-contracted.csv,1
93,./archive\UNCOVER\harvard_global_health_institute\hospital-capacity-by-state-40-population-contracted.csv,1
94,./archive\UNCOVER\harvard_global_health_institute\hospital-capacity-by-state-60-population-contracted.csv,1
99,./archive\UNCOVER\hifld\hifld\hospitals.csv,1
137,./archive\UNCOVER\statistics_canada\open-database-of-healthcare-facilities.csv,1
107,./archive\UNCOVER\howsmyflattening\ontario-testing-data.csv,1
108,./archive\UNCOVER\ihme\projected-hospital-resource-use-based-on-covid-19-deaths.csv,1
133,./archive\UNCOVER\regional_sources\department_of_civil_protection\covid-19-italy-situation-monitoring-by-region.csv,1
114,./archive\UNCOVER\johns_hopkins_csse\johns-hopkins-covid-19-daily-dashboard-cases-by-country.csv,1
115,./archive\UNCOVER\johns_hopkins_csse\johns-hopkins-covid-19-daily-dashboard-cases-by-states.csv,1
126,./archive\UNCOVER\ontario_government\status-of-covid-19-cases-in-ontario (1).csv,1
184,./archive\UNCOVER_v4\UNCOVER\johns_hopkins_csse\johns-hopkins-covid-19-daily-dashboard-cases-by-country.csv,1
166,./archive\UNCOVER_v4\UNCOVER\covid_tracking_project\covid-statistics-for-all-us-totals.csv,1
39,./archive\RDSC-07-30-Update\RDSC-07-30-Update\johns_hopkins_csse\johns-hopkins-covid-19-daily-dashboard-cases-by-states.csv,1
5,./archive\RDSC-07-30-Update\RDSC-07-30-Update\coders_against_covid\crowd-sourced-covid-19-testing-locations.csv,1
38,./archive\RDSC-07-30-Update\RDSC-07-30-Update\johns_hopkins_csse\johns-hopkins-covid-19-daily-dashboard-cases-by-country.csv,1
19,./archive\RDSC-07-30-Update\RDSC-07-30-Update\department_of_civil_protection\covid-19-italy-situation-monitoring-by-region.csv,1
17,./archive\RDSC-07-30-Update\RDSC-07-30-Update\covid_tracking_project\covid-statistics-for-all-us-daily-updates.csv,1
22,./archive\RDSC-07-30-Update\RDSC-07-30-Update\github\crowd-sourced-covid-19-testing-locations.csv,1
201,./archive\UNCOVER_v4\UNCOVER\regional_sources\department_of_civil_protection\covid-19-italy-situation-monitoring-by-region.csv,1
194,./archive\UNCOVER_v4\UNCOVER\ontario_government\status-of-covid-19-cases-in-ontario.csv,1
32,./archive\RDSC-07-30-Update\RDSC-07-30-Update\ihme\projected-hospital-resource-use-based-on-covid-19-deaths.csv,1
207,./archive\UNCOVER_v4\UNCOVER\statistics_canada\open-database-of-healthcare-facilities.csv,1

In [28]:
df=pd.read_csv('./archive\RDSC-07-30-Update\RDSC-07-30-Update\howsmyflattening\ontario-icu-capacity.csv')

In [29]:
df

,Unnamed: 0,id,date,icu_level,region,lhin,critical_care_beds,critical_care_patients,vented_beds,vented_patients,suspected_covid,suspected_covid_ventilator,confirmed_positive,confirmed_negative,confirmed_positive_ventilator
0,0,36,2020-03-28,Level 3,West,1. ESC,73,50,71,32,21.0,14.0,8,1.0,8
1,1,37,2020-03-28,Level 3,West,2. SW,105,73,96,25,19.0,9.0,8,7.0,6
2,2,38,2020-03-28,Level 3,West,3. WW,64,55,58,27,20.0,11.0,7,4.0,5
3,3,39,2020-03-28,Level 3,West,4. HNHB,159,108,151,56,23.0,10.0,6,13.0,4
4,4,40,2020-03-28,Level 3,Central,5. CW,46,27,26,18,5.0,4.0,2,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,501,652,2020-06-26,NaN,Toronto,Toronto Central,500,304,393,115,NaN,NaN,19,NaN,14
502,502,653,2020-06-26,NaN,West,Erie St. Clair,133,64,119,18,NaN,NaN,1,NaN,0
503,503,654,2020-06-26,NaN,West,Hamilton Niagara Haldimand Brant,471,218,372,62,NaN,NaN,4,NaN,3
504,504,655,2020-06-26,NaN,West,South West,341,140,252,36,NaN,NaN,1,NaN,0
505,505,656,2020-06-26,NaN,West,Waterloo Wellington,149,82,109,27,NaN,NaN,2,NaN,2

In [30]:
df=pd.read_csv('./archive\RDSC-07-30-Update\RDSC-07-30-Update\ihme\projected-hospital-resource-use-based-on-covid-19-deaths.csv')

In [31]:
df.describe()

,Unnamed: 0,allbed_mean,allbed_lower,allbed_upper,icubed_mean,icubed_lower,icubed_upper,invven_mean,invven_lower,invven_upper,...,newicu_upper,totdea_mean,totdea_lower,totdea_upper,bedover_mean,bedover_lower,bedover_upper,icuover_mean,icuover_lower,icuover_upper
count,9955.000000,9955.000000,9955.000000,9955.000000,9955.000000,9955.000000,9955.000000,9955.000000,9955.000000,9955.000000,...,9955.000000,9955.000000,9955.000000,9955.000000,9955.000000,9955.000000,9955.000000,9955.000000,9955.000000,9955.000000
mean,4977.000000,1758.906128,819.979267,3088.379491,261.588478,121.338798,460.996763,209.271398,96.998467,368.987200,...,58.475706,1724.991041,859.215806,2920.552202,320.515173,110.819203,943.942575,96.366670,35.246707,250.535948
std,2873.905299,11892.348666,6202.157398,19788.421797,1801.074114,943.431058,2992.703239,1440.860860,754.538136,2394.885319,...,376.523962,8081.765376,4033.381752,13627.554699,3546.468580,1354.303561,7585.648221,869.233802,366.796952,1850.566195
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2488.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4977.000000,15.248602,0.000000,36.740000,1.474000,0.000000,4.000000,1.183310,0.000000,3.187500,...,0.000000,278.213000,125.975000,427.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,7465.500000,552.301521,155.499219,972.690625,75.851467,19.300000,137.357679,60.678837,15.341406,109.772135,...,18.012500,1148.609000,525.925000,2041.150000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,9954.000000,224321.278685,122879.215701,352380.170346,34799.789421,19261.697586,54083.004466,27839.054391,15383.136211,43329.602358,...,6847.868412,82140.880000,39174.300000,141994.875000,71804.569095,26783.676250,146185.809796,18338.609751,7793.404581,35669.458150

In [32]:
df=pd.read_csv('./archive/UNCOVER/covid_tracking_project/covid-statistics-by-us-states-totals.csv')

In [33]:
df

,state,positive,positivescore,negativescore,negativeregularscore,commercialscore,grade,score,notes,dataqualitygrade,...,checktimeet,death,hospitalized,total,totaltestresults,posneg,fips,datemodified,datechecked,hash
0,AK,351,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",B,...,4/28 15:14,9,NaN,17089,17089,17089,2,2020-04-28 18:50:00,2020-04-28 19:14:00,f5f8fd60d9ab9000b01078ebb64a6ead70991838
1,AL,6687,1.0,1.0,0.0,1.0,B,3.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",B,...,4/28 16:23,242,911.0,75827,75827,75827,1,2020-04-28 04:00:00,2020-04-28 20:23:00,ce913fed81a2519acc5fad3fa47a46d5de9791a7
2,AR,3111,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",B,...,4/28 15:15,52,NaN,40671,40671,40671,5,2020-04-28 13:00:00,2020-04-28 19:15:00,db047c4c735a3fed6ceec83410b67647820351dc
3,AZ,6948,1.0,1.0,0.0,1.0,B,3.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",A+,...,4/28 14:04,293,1095.0,67438,67438,67438,4,2020-04-27 04:00:00,2020-04-28 18:04:00,ed30f69fbcb735ea556fd73c6527c52e2ea64d95
4,CA,45031,1.0,1.0,0.0,1.0,B,3.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",B,...,4/28 16:03,1809,NaN,577608,577608,577608,6,2020-04-27 04:00:00,2020-04-28 20:03:00,6465238e0ca54eddc1da1a09b2a529005bdefba6
5,CO,13879,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",B,...,4/28 16:23,706,2485.0,66341,66341,66341,8,2020-04-27 04:00:00,2020-04-28 20:23:00,f063559b88e0fef04e412c6a95728c0208e00ab1
6,CT,26312,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",C,...,4/28 16:32,2089,NaN,92745,92745,92745,9,2020-04-28 20:00:00,2020-04-28 20:32:00,418370a422d564a36e7c8b83b754201279cf4f41
7,DC,3994,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",B,...,4/28 15:18,190,NaN,18885,18885,18885,11,2020-04-27 04:00:00,2020-04-28 19:18:00,d822076baa77d9b19ca7f2b6f4970948155367e2
8,DE,4575,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",B,...,4/28 14:14,137,NaN,21180,21180,21180,10,2020-04-27 22:00:00,2020-04-28 18:14:00,f1dc2b68833acf698c626222df17522eb2018cc4
9,FL,32846,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",C,...,4/28 14:54,1154,5266.0,368091,366875,366875,12,2020-04-28 13:36:00,2020-04-28 18:54:00,3d5078fbfdf9793d44cf19135faf64151c2c16d8
10,GA,24615,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",A,...,4/28 14:07,1026,4814.0,140020,140020,140020,13,2020-04-28 17:25:00,2020-04-28 18:07:00,c948aec0c005525755302a694cb2c17cf4a05bcf
11,HI,607,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",B,...,4/28 14:47,16,68.0,29183,29183,29183,15,2020-04-27 22:00:00,2020-04-28 18:47:00,e0360e5ebabaa4c59ccb4af5a030b9daae9e3c6d
12,IA,6376,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",B,...,4/28 14:14,136,NaN,39823,39823,39823,19,2020-04-27 16:00:00,2020-04-28 18:14:00,803d290d7457e4bb1413b79dfc53387b34d7a5fe
13,ID,1917,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",C,...,4/28 14:50,58,172.0,20052,20052,20052,16,2020-04-27 23:00:00,2020-04-28 18:50:00,60ca8d2476d6950067ecd37420a2573b9e015445
14,IL,48102,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",A,...,4/28 16:01,2125,NaN,242189,242189,242189,17,2020-04-28 04:00:00,2020-04-28 20:01:00,68394edeb48c5c0c993baf356c1cb7fbf5902566
15,IN,16588,1.0,1.0,1.0,0.0,B,3.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",A,...,4/28 14:17,901,NaN,87181,87181,87181,18,2020-04-28 03:59:00,2020-04-28 18:17:00,19a1e429793f41c5ba7894f7a8173c1789628184
16,KS,3491,1.0,1.0,1.0,0.0,B,3.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",C,...,4/28 14:22,124,504.0,28090,28090,28090,20,2020-04-28 14:00:00,2020-04-28 18:22:00,8251858f19b6f48730478b6ff75d13add0671c38
17,KY,4146,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",A,...,4/28 14:58,213,1281.0,48799,48799,48799,21,2020-04-27 21:00:00,2020-04-28 18:58:00,c6859146d8c311e5aac914bf21b4acedc15715ae
18,LA,27286,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",B,...,4/28 14:28,1801,NaN,151108,151108,151108,22,2020-04-28 17:00:00,2020-04-28 18:28:00,1e3cd4a22f8ec0e2648520647e151fbe0ba9518e
19,MA,58302,1.0,1.0,0.0,1.0,B,3.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",B,...,4/28 16:34,3153,5515.0,254500,254500,254500,25,2020-04-28 20:00:00,2020-04-28 20:34:00,c309321650b531b1a319c8e8dc7afffdecd1b88a
20,MD,20113,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",A,...,4/28 15:52,1016,4268.0,107785,107785,107785,24,2020-04-28 14:00:00,2020-04-28 19:52:00,587c7b2f1d5d740d50c133c7cf3d79bab6a028a3
21,ME,1040,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",B,...,4/28 14:29,51,163.0,17824,17824,17824,23,2020-04-28 15:45:00,2020-04-28 18:29:00,0eb57c187742d59d3b0165f32bf18f0ebc3410a3
22,MI,39262,1.0,1.0,0.0,1.0,B,3.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",A+,...,4/28 16:21,3567,NaN,164805,164805,164805,26,2020-04-28 15:00:00,2020-04-28 20:21:00,e9a9aa47222faf95082ca2cb25e9da708d16aa48
23,MN,4181,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",A,...,4/28 14:32,301,912.0,63829,63829,63829,27,2020-04-27 21:00:00,2020-04-28 18:32:00,9a14b8c0ec1d91dbbfa8b65a72f78bf049492d6c
24,MO,7303,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",A,...,4/28 15:07,314,NaN,73503,73503,73503,29,2020-04-28 19:00:00,2020-04-28 19:07:00,9021ea81e6028ba06cd411c93aadd930a5229719
25,MS,6342,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",B,...,4/28 14:36,239,1088.0,64412,64412,64412,28,2020-04-27 23:00:00,2020-04-28 18:36:00,b74ed66e8c661abfa527b36c3e5ff39452867511
26,MT,451,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",C,...,4/28 14:38,15,61.0,13191,13191,13191,30,2020-04-28 04:00:00,2020-04-28 18:38:00,5d92f499d6c4c11c2eff5cc6f4a0b4888cdd826f
27,NC,9568,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",B,...,4/28 14:39,342,NaN,112752,112752,112752,37,2020-04-28 15:00:00,2020-04-28 18:39:00,096f3f249eaad0251579ed743c2e4502ea57af6e
28,ND,991,1.0,1.0,1.0,0.0,B,3.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",C,...,4/28 14:40,19,79.0,23723,23723,23723,38,2020-04-28 17:00:00,2020-04-28 18:40:00,23952cda813f097c53c00271ac12f1116a40ef04
29,NE,3358,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",D,...,4/28 15:14,55,NaN,23605,23605,23605,31,2020-04-27 23:45:00,2020-04-28 19:14:00,4c102d03427cb85f4be0cef75003889aff4cab21
30,NH,1938,1.0,1.0,1.0,0.0,B,3.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",C,...,4/28 15:50,60,246.0,20368,20145,20145,33,2020-04-27 13:00:00,2020-04-28 19:50:00,6ba0b455af0779e38d232b0555a8a320bfac62a3
31,NJ,113856,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",A+,...,4/28 15:52,6442,NaN,234359,234359,234359,34,2020-04-28 17:00:00,2020-04-28 19:52:00,a9761e3fa53afb32d90441175b62ff545d7fe26e
32,NM,2823,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",C,...,4/28 15:11,104,481.0,58803,58803,58803,35,2020-04-27 22:04:00,2020-04-28 19:11:00,6f38c6869e6effe51f06b1859188bfb356d233af
33,NV,4805,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",F,...,4/28 16:02,219,NaN,40119,40119,40119,32,2020-04-28 14:00:00,2020-04-28 20:02:00,8d65c1e4efbcb85f60ba9bfde3ac25e795ebc118
34,NY,295106,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",B,...,4/28 16:23,17638,64275.0,844994,844994,844994,36,2020-04-28 04:00:00,2020-04-28 20:23:00,02cee9e9406f20d17406830305c67c7f7cbd50cc
35,OH,16128,1.0,1.0,0.0,1.0,B,3.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",B,...,4/28 15:34,799,3340.0,122706,122706,122706,39,2020-04-28 18:00:00,2020-04-28 19:34:00,b680b803f01ab8d9ed771c703b998b3bd0be7352
36,OK,3410,1.0,1.0,0.0,1.0,B,3.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",A,...,4/28 16:21,207,656.0,59699,59699,59699,40,2020-04-28 04:00:00,2020-04-28 20:21:00,200835369f6cc8480029e31b6cdc83728f7ba9e9
37,OR,2354,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",A,...,4/28 15:31,92,554.0,51198,51198,51198,41,2020-04-27 15:00:00,2020-04-28 19:31:00,a1e3e13e24905096db7cbfe4f5d5d3d758335e3b
38,PA,43264,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",B,...,4/28 15:04,1716,NaN,209088,209088,209088,42,2020-04-28 04:00:00,2020-04-28 19:04:00,822d02d36e4a336d12144731409eec5c73c6994f
39,RI,7926,1.0,1.0,1.0,0.0,B,3.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",A+,...,4/28 15:19,239,732.0,57693,57693,57693,44,2020-04-28 16:00:00,2020-04-28 19:19:00,13696baaacc342edafa08aa9cbac343ca6fcc5e6
40,SC,5613,1.0,1.0,1.0,0.0,B,3.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",B,...,4/28 14:24,177,944.0,52145,52145,52145,45,2020-04-27 20:30:00,2020-04-28 18:24:00,f31adfc0cd02088d8289840bfdb33aa7ebdb07da
41,SD,2313,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",C,...,4/28 16:32,11,157.0,16612,16612,16612,46,2020-04-27 22:00:00,2020-04-28 20:32:00,8db4141335769245979af1be6a37512790728731
42,TN,10052,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",B,...,4/28 15:36,188,894.0,161928,161928,161928,47,2020-04-28 19:00:00,2020-04-28 19:36:00,59a4d80b654857bea86b2048b8e5851d2af9ec05
43,TX,26171,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",B,...,4/28 14:31,690,NaN,300384,300384,300384,48,2020-04-28 17:00:00,2020-04-28 18:31:00,964d7fd241d95b9210667f506c0ca89a16d74eb3
44,UT,4343,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",C,...,4/28 14:44,45,370.0,102439,102439,102439,49,2020-04-28 19:00:00,2020-04-28 18:44:00,688409cd8ae4fa6f3cef5f4f72b643b66026fd7d
45,VA,13794,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",B,...,4/28 16:05,492,3422.0,83313,82753,82753,51,2020-04-27 21:00:00,2020-04-28 20:05:00,b8b967b36db98c0e3598afa7482009789834f3e0
46,VT,862,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",C,...,4/28 16:25,47,NaN,15215,15215,15215,50,2020-04-28 14:42:00,2020-04-28 20:25:00,e6762e7faa544f66cfa9266415c01d1ca2260abf
47,WA,13686,0.0,1.0,0.0,1.0,C,2.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",B,...,4/28 16:00,765,NaN,179679,179679,179679,53,2020-04-27 06:59:00,2020-04-28 20:00:00,920c41949623bcb5fa3fbf3f5376200fdb2d6411
48,WI,6289,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",A,...,4/28 15:38,300,1456.0,70017,69824,69824,55,2020-04-28 20:00:00,2020-04-28 19:38:00,3a07dae4ffd6c9297581c4830cbcd7c44530aeb3
49,WV,1079,1.0,1.0,1.0,0.0,B,3.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",C,...,4/28 15:50,37,NaN,43055,43055,43055,54,2020-04-28 14:00:00,2020-04-28 19:50:00,ad2b5c52e8f8be871920099295a74a768e9761f7
50,WY,389,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",C,...,4/28 15:46,7,56.0,8615,8615,8615,56,2020-04-27 21:05:00,2020-04-28 19:46:00,8a2ae61574964fcfdd97901777a326db8fa2e90c
51,PR,1400,1.0,1.0,1.0,1.0,A,4.0,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",D,...,4/28 15:30,86,NaN,12653,10713,10713,72,2020-04-28 10:30:00,2020-04-28 19:30:00,588aaabd3558fda4fc2d9a3f84088f49af77d569
52,AS,0,NaN,NaN,NaN,NaN,NaN,NaN,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",F,...,4/28 16:12,0,NaN,20,3,3,60,2020-04-19 04:00:00,2020-04-28 20:12:00,56cb111e0e67054c025020a8b825a6cadf437f80
53,GU,145,NaN,NaN,NaN,NaN,NaN,NaN,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",D,...,4/28 14:43,5,NaN,1683,1683,1683,66,2020-04-28 13:15:00,2020-04-28 18:43:00,3faa6493fb85863f5711d7b2e4c09fb9accb2428
54,MP,14,NaN,NaN,NaN,NaN,NaN,NaN,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",D,...,4/28 15:12,2,NaN,65,65,65,69,2020-04-28 04:00:00,2020-04-28 19:12:00,e3ef07fbed1b3687c6f54f28de7c15117bd6d61b
55,VI,59,NaN,NaN,NaN,NaN,NaN,NaN,"Please stop using the ""total"" field. Use ""totalTestResults"" instead. As of 4/24/20, ""grade"" is deprecated. Please use ""dataQualityGrade"" instead.",C,...,4/28 15:40,4,NaN,835,778,778,78,2020-04-27 04:00:00,2020-04-28 19:40:00,7a8802bec2ccf1284c78a7fd4880be1b4afc8622

In [34]:
df=pd.read_csv('./archive\RDSC-07-30-Update/RDSC-07-30-Update/howsmyflattening/ontario-testing-data.csv')

In [35]:
df

,Unnamed: 0,id,date,negative,investigation,positive,resolved,deaths,total,hospitalized,icu,ventilator
0,0,50,2020-02-21,483,12,3,3,0,498,NaN,NaN,NaN
1,1,4,2020-02-24,540,9,4,3,0,553,NaN,NaN,NaN
2,2,51,2020-02-25,568,21,4,3,0,593,NaN,NaN,NaN
3,3,41,2020-02-05,96,43,3,0,0,150,NaN,NaN,NaN
4,4,42,2020-02-06,104,62,3,0,0,169,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
162,162,297,2020-07-24,1924954,25550,38405,34100,2758,1988909,141.0,31.0,20.0
163,163,298,2020-07-25,1954192,26078,38543,34240,2759,2018813,97.0,30.0,21.0
164,164,299,2020-07-26,1988277,18000,38680,34359,2763,2044957,87.0,29.0,21.0
165,165,300,2020-07-27,2021573,9249,38799,34461,2764,2069621,82.0,30.0,18.0
166,166,301,2020-07-28,2035126,12919,38910,34567,2768,2086955,96.0,31.0,18.0

In [36]:
df.isnull().sum()

Unnamed: 0        0
id                0
date              0
negative          0
investigation     0
positive          0
resolved          0
deaths            0
total             0
hospitalized     45
icu              36
ventilator       45
dtype: int64

In [37]:
df=pd.read_csv('./archive\RDSC-07-30-Update/RDSC-07-30-Update/covid_tracking_project/covid-statistics-by-us-states-daily-updates.csv')

In [38]:
df

,Unnamed: 0,date,state,positive,negative,pending,hospitalizedcurrently,hospitalizedcumulative,inicucurrently,inicucumulative,...,posneg,deathincrease,hospitalizedincrease,hash,commercialscore,negativeregularscore,negativescore,positivescore,score,grade
0,0,2020-07-29,AK,3442.0,220222.0,NaN,45.0,NaN,NaN,NaN,...,223664,0,0,e3c05df1cf92b9c80941cec8daaf723905e7a0dd,0,0,0,0,0,NaN
1,1,2020-07-29,AL,83782.0,584493.0,NaN,1598.0,9893.0,NaN,1109.0,...,668275,47,0,a7b049cfd14780e56e6ef98fb2aba9f82fe89838,0,0,0,0,0,NaN
2,2,2020-07-29,AR,40968.0,454637.0,NaN,508.0,2747.0,NaN,NaN,...,495605,6,61,e1fad45c3dbf16efc7ddd84400b3629a9c824a71,0,0,0,0,0,NaN
3,3,2020-07-29,AS,0.0,1037.0,NaN,NaN,NaN,NaN,NaN,...,1037,0,0,62e46ea05669252eb426e2da4a1e822abcf86cb3,0,0,0,0,0,NaN
4,4,2020-07-29,AZ,168273.0,733156.0,NaN,2424.0,10060.0,800.0,NaN,...,901429,46,666,9c7e10ce8b2fb77e7a69df1d09c60accaab1a498,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8188,8188,2020-01-26,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,...,2,0,0,7acb526e14f20a29cc74a0b32a37328bc6eac6c2,0,0,0,0,0,NaN
8189,8189,2020-01-25,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,...,2,0,0,9b52ca94dd2a996822542ea5f17a7363e7ad91cf,0,0,0,0,0,NaN
8190,8190,2020-01-24,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,...,2,0,0,094154f68e74bfc30b977cdee888f9c07be4360e,0,0,0,0,0,NaN
8191,8191,2020-01-23,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,...,2,0,0,e16af2a6a8f060355ff5ba499a28309a262c0b1e,0,0,0,0,0,NaN
8192,8192,2020-01-22,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,...,2,0,0,8f8db794931706272489cddd51e917a4a69c8c9b,0,0,0,0,0,NaN